export const INVENTORY_UNITS = [
  { label: 'Piece (pcs)', value: 'pcs' },
  { label: 'Dozen (doz)', value: 'doz' },
  { label: 'Pair (pr)', value: 'pr' },
  { label: 'Box (box)', value: 'box' },
  { label: 'Carton (ctn)', value: 'ctn' },
  { label: 'Kilogram (kg)', value: 'kg' },
  { label: 'Gram (g)', value: 'g' },
  { label: 'Milligram (mg)', value: 'mg' },
  { label: 'Ton (t)', value: 't' },
  { label: 'Liter (L)', value: 'L' },
  { label: 'Milliliter (ml)', value: 'ml' },
  { label: 'Cubic Meter (m3)', value: 'm3' },
  { label: 'Meter (m)', value: 'm' },
  { label: 'Centimeter (cm)', value: 'cm' },
  { label: 'Foot (ft)', value: 'ft' },
  { label: 'Square Meter (m2)', value: 'm2' },
  { label: 'Square Foot (sq_ft)', value: 'sq_ft' },
  { label: 'Hour (hr)', value: 'hr' },
  { label: 'Day (day)', value: 'day' },
  { label: 'Week (wk)', value: 'wk' },
  { label: 'Month (mo)', value: 'mo' },
  { label: 'Job (job)', value: 'job' },
  { label: 'Task (task)', value: 'task' },
  { label: 'Service (svc)', value: 'svc' },
  { label: 'Visit (visit)', value: 'visit' },
  { label: 'Bottle (btl)', value: 'btl' },
  { label: 'API Call (call)', value: 'call' },
  { label: 'Gigabyte (GB)', value: 'GB' },
  { label: 'Kilowatt Hour (kWh)', value: 'kWh' },
  { label: 'User (usr)', value: 'usr' },
  { label: 'License (lic)', value: 'lic' },
  { label: 'Indian Rupee (INR)', value: 'INR' },
  { label: 'US Dollar (USD)', value: 'USD' },
];
